### ISSUE TITLE
SQLiteDatabase.java line null

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#103]
#### in net.sqlcipher.database.SQLiteDatabase.dbopen

* Number of crashes: 43
* Impacted devices: 43

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/56169a71f5d3a7f76ba66844](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/56169a71f5d3a7f76ba66844)

**Comment by mndfcked** [comment]
Still not fixed. https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/56169a71f5d3a7f76ba66844
