### ISSUE TITLE
Editor.java line 4260

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#139]
#### in android.widget.Editor$SelectionStartHandleView.positionAtCursorOffset
- Number of crashes: 49
- Impacted devices: 34

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/561ba1edf5d3a7f76bbd882f](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/561ba1edf5d3a7f76bbd882f)

**Comment by mndfcked** [comment]
No app issue
