### ISSUE TITLE
NavigationMenuPresenter.java line 174

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#142]
#### in android.support.design.internal.NavigationMenuPresenter.onRestoreInstanceState
- Number of crashes: 49
- Impacted devices: 15

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/571023e6ffcdc04250b94769](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/571023e6ffcdc04250b94769)

**Comment by mndfcked** [comment]
This is an Android 2.x error only. Since we don't support it anymore, no fix needed.
