### ISSUE TITLE
OperatorMapResponseToBodyOrError.java line 43

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#156]
#### in retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext

* Number of crashes: 48
* Impacted devices: 8

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/58831a6b0aeb16625b5b2674](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/58831a6b0aeb16625b5b2674)

**Comment by mndfcked** [comment]
Non-fatal only 404 errors logged
