### ISSUE TITLE
AndroidPlatform.java line 61

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#160]
#### in okhttp3.internal.platform.AndroidPlatform.connectSocket

* Number of crashes: 48
* Impacted devices: 27

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/58cd63d00aeb16625b8dcd34](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/58cd63d00aeb16625b8dcd34)

**Comment by mndfcked** [comment]
Non-fatal connection timeout
