### ISSUE TITLE
FramedStream.java line 600

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#162]
#### in okhttp3.internal.framed.FramedStream$StreamTimeout.newTimeoutException

* Number of crashes: 46
* Impacted devices: 29

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/5922caa9be077a4dcc10743e](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/5922caa9be077a4dcc10743e)

**Comment by mndfcked** [comment]
Not an app issue
