### ISSUE TITLE
SignInFragment.java line 575

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#38]
#### in de.elanev.studip.android.app.backend.net.oauth.SignInFragment$5.onErrorResponse

* Number of crashes: 49
* Impacted devices: 47

There's a lot more information about this crash on crashlytics.com:
[https://crashlytics.com/elanev/android/apps/de.elanev.studip.android.app/issues/53f59014e3de5099bab260c0](https://crashlytics.com/elanev/android/apps/de.elanev.studip.android.app/issues/53f59014e3de5099bab260c0)

**Comment by mndfcked** [comment]
Fixed with 31abb2a
