### ISSUE TITLE
Planner Landscape view

### ISSUE THREAD

**Issue by mndfcked** [elan-ev/StudIPAndroidApp#44]
Display an optimized events overview when the user switches to landscape mode.
Todo:
* Mock
* Implementation
* Tests

**Comment by mndfcked** [comment]
Todo @aklassen Mockup

**Comment by aklassen** [comment]
![mockup](https://cloud.githubusercontent.com/assets/38511/9682298/ac6791ca-5305-11e5-90c3-eb217fb7405f.jpg)

Das sollte als Vorlage dienen.
