### ISSUE TITLE
???

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#47]
#### in net.sqlcipher.database.SQLiteDatabase.dbopen

* Number of crashes: 48
* Impacted devices: 47

There's a lot more information about this crash on crashlytics.com:
[https://crashlytics.com/elanev/android/apps/de.elanev.studip.android.app/issues/543e4782e3de5099ba0df5bc](https://crashlytics.com/elanev/android/apps/de.elanev.studip.android.app/issues/543e4782e3de5099ba0df5bc)

**Comment by mndfcked** [comment]
Tracking in #55
