### ISSUE TITLE
Course Overview HTML parsing

### ISSUE THREAD

**Issue by mndfcked** [elan-ev/StudIPAndroidApp#48]
The description in the course overview fragment may contain HTML Tags. These should be parsed correctly.

**Comment by aklassen** [comment]
I'll check that.

**Comment by aklassen** [comment]
Weisst du wo genau diese HTML-Tags / Kommentare auftauchen? Ich finde die gerade nicht bei der Übersicht.

**Comment by mndfcked** [comment]
There is no way that HTML can be in the description property.
