### ISSUE TITLE
net.sqlcipher.database.SQLiteException: not an error while dbopen

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#55]
#### in net.sqlcipher.database.SQLiteDatabase.dbopen

* Number of crashes: 49
* Impacted devices: 47

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/544e1da5e3de5099ba246a5d](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/544e1da5e3de5099ba246a5d)

**Comment by mndfcked** [comment]
Probably related to sqlcipher/android-database-sqlcipher#139
