### ISSUE TITLE
CourseRecordingsFragment.java line 142

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#57]
#### in de.elanev.studip.android.app.frontend.courses.CourseRecordingsFragment.onItemClick

* Number of crashes: 49
* Impacted devices: 33

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/544b61f6e3de5099ba20e382](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/544b61f6e3de5099ba20e382)

**Comment by mndfcked** [comment]
Confirmed. Sometimes the "presenter_download" entry in the response can be null. Add null check and show user error.

**Comment by mndfcked** [comment]
Fixed by 164ba5f
