### ISSUE TITLE
SwipeRefreshLayout.java line 530

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#61]
#### in android.support.v4.widget.SwipeRefreshLayout.startRefresh

* Number of crashes: 50
* Impacted devices: 35

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/544a9e7ee3de5099ba1fe860](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/544a9e7ee3de5099ba1fe860)

**Comment by mndfcked** [comment]
Already fixed
