### ISSUE TITLE
RestIpProvider.java line 1380

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#64]
#### in 

* Number of crashes: 21
* Impacted devices: 21

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/54bc3d8c65f8dfea15a1f700](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/54bc3d8c65f8dfea15a1f700)

**Comment by mndfcked** [comment]
Fixed by d70f21b
