### ISSUE TITLE
Übersicht der Aufzeichnungen wieder anzeigen

### ISSUE THREAD

**Issue by aklassen** [elan-ev/StudIPAndroidApp#72]
wie besprochen

**Comment by mndfcked** [comment]
Ist schon länger her als wir es besprochen haben. Deshalb weiß ich nicht mehr was überhaupt besprochen wurde. Was ich auf jedenfall sagen kann, dass über die API nicht mehr das oc_matterhorn Modul bei den Courses ausgegeben wird. Und davon wird das abhängig gemacht. Bitte prüfen.

**Comment by mndfcked** [comment]
Server Error
