### ISSUE TITLE
Events eines Kurses (aka Ablaufplan) wird anscheinend nicht sinnvoll gefüllt

### ISSUE THREAD

**Issue by aklassen** [elan-ev/StudIPAndroidApp#74]
Habe heute festgestellt, dass die Terminübersicht für einem Kurs nicht mehr sinnvolle Listeneinträge enthält.  Ich habe mal ein paar Screenshots angehangen. 

Das Problem tauch mit dem Rest.IP-Plugin V0.9.9.4 und V0.9.9.7 auf.
![screenshot_2015-05-28-23-18-02](https://cloud.githubusercontent.com/assets/38511/7871457/48361e1e-0590-11e5-9fc0-740ec85a167c.png)
![screenshot_2015-05-28-23-18-10](https://cloud.githubusercontent.com/assets/38511/7871458/4837188c-0590-11e5-91d4-5ae0e9eb6d89.png)

**Comment by mndfcked** [comment]
API Response entries for Title, Room and/or Description are null in these particular courses. If nothing is there to display, nothing will be displayed. However the App should not display empty list entries. This will be tracked in #75.

**Comment by aklassen** [comment]
Das Thema ist leider noch nicht durch!
