### ISSUE TITLE
Prevent displaying empty entries in course events list

### ISSUE THREAD

**Issue by mndfcked** [elan-ev/StudIPAndroidApp#75]
When the response entries for room, description and title are null, the course events list displays empty entries. Like in #74. If the entries are null, the list item should be deleted from the list.

**Comment by aklassen** [comment]
Mit der neueren API Version (0.9.9.7) wird leider kein Default-Titel bei leeren Feldern generiert.  Man müsste diesen  jetzt selbständig in der App generieren. Hier das damalige Schema für den Default-Titel: `title: "Di., 12.10.2004, 11:00 - 12:00"`

**Comment by aklassen** [comment]
Ich muss mal eben dan der Prio und Milestone schrauben. Auch wenn es kein Bug unsererseits ist, ist es leider ein Showstopper.
