### ISSUE TITLE
Subject bei den Feedbackmails wird nicht richtig gesetzt

### ISSUE THREAD

**Issue by aklassen** [elan-ev/StudIPAndroidApp#77]
Möchte man vor der Authentifizierung eine Feedbackmail aus der App verschicken, kann es passieren, dass die entsprechende Betreffzeile nicht richtig generiert wird. Konkret taucht das Problem bei einem Nutzer der Uni Hannover auf. Hier wurde dann im Betreff `[Universität Osnabrück]` gesetzt, obwohl der Standort Hannover ausgewählt wurde.

**Comment by mndfcked** [comment]
Fixed with 9e7ba87
Wenn man nicht authentifiziert ist, geht Feedback direkt an uns.
