### ISSUE TITLE
DiskBasedCache.java line 322

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#90]
#### in com.android.volley.toolbox.DiskBasedCache.streamToBytes

* Number of crashes: 11
* Impacted devices: 11

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/55489a0d5141dcfd8fac0b20](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/55489a0d5141dcfd8fac0b20)

**Comment by mndfcked** [comment]
Will be covered with #117
