### ISSUE TITLE
MotionEvent.java line 0

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#96]
#### in android.view.MotionEvent.nativeGetAxisValue

* Number of crashes: 47
* Impacted devices: 47

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/5544b9bd5141dcfd8fa53a15](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/5544b9bd5141dcfd8fa53a15)

**Comment by mndfcked** [comment]
Android framework issue of old App version.
